### ISSUE TITLE
Each list view and Task list view is a little different — many random inconsistencies

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [Tendrl/dashboard#251]
There are different styling of the widgets in the list view, e.g. filter, sort key — non confirming to PatternFly (http://www.patternfly.org/pattern-library/content-views/list-view/list-view.html).  See the filter widget controls and sort key widget — not only do they differ from list view to list view.
sometimes the widget is sharp edges, sometimes it’s rounded.  For PF, it’s all sharp edges/

**Comment by cloudbehl** [comment]
@Tendrl/qe The bug is fixed from UI team. Please verify on the new build[1] available.

[1]. tendrl-dashboard-1.2.1-04_17_2017_17_24_12.noarch.rpm

**Comment by julienlim** [comment]
@cloudbehl This is not yet fixed.  I've attached some screenshots of what it looks like in the list views, and I've also attached what it should look like from a PatternFly perspective.

<img width="604" alt="screen shot 2017-04-19 at 4 06 44 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200029/ef2325f4-251a-11e7-89bc-c1132b076adf.png">
<img width="608" alt="screen shot 2017-04-19 at 4 06 54 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200028/ef225cb4-251a-11e7-8a2f-6c492f8e5ce0.png">
<img width="669" alt="screen shot 2017-04-19 at 4 07 01 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200030/ef24a186-251a-11e7-899a-e1c8cde6b332.png">
<img width="676" alt="screen shot 2017-04-19 at 4 07 11 pm" src="https://cloud.githubusercontent.com/assets/5589919/25200031/ef2f2d86-251a-11e7-873d-6a58fbcd4d72.png">
<img width="788" alt="pf - list view widgit" src="https://cloud.githubusercontent.com/assets/5589919/25200032/ef30ec7a-251a-11e7-9479-bcb135feab81.png">

**Comment by nthomas-redhat** [comment]
@julienlim , I could see that the widget styling is conforming to patternfly now. Could please check again and let us know if there is any discrepancies?

**Comment by julienlim** [comment]
@nthomas-redhat @gnehapk @cloudbehl It's still not fixed.  Note the rounded edges in the styling.  PF uses straight edges, and not rounded edges on the fields and input fields.  There's also a grey vertical bar that is sometimes there and sometimes not there in some of the list views.
